# Generated by Django 4.1.10 on 2023-07-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_create_courts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(choices=[('Stadium Court', 'Stadium Court'), ('Court 1', 'Court 1'), ('Court 2', 'Court 2'), ('Court 3', 'Court 3'), ('Court 4', 'Court 4'), ('Court 5', 'Court 5'), ('Court 6', 'Court 6'), ('Court 7', 'Court 7')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='reservations.date'),
        ),
    ]
