# Generated by Django 4.1.10 on 2023-08-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_court_name_alter_participation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='reservations.activity'),
        ),
        migrations.AlterField(
            model_name='date',
            name='capacity',
            field=models.IntegerField(default=4, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
