# Generated by Django 4.1.10 on 2023-08-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_date_activity_alter_date_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.activity'),
        ),
    ]
