# Generated by Django 4.1.10 on 2023-08-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_date_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_playing',
        ),
        migrations.AddField(
            model_name='member',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
