# Generated by Django 4.1.10 on 2023-08-22 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_member_is_playing_member_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='assigned_pros',
            field=models.ManyToManyField(blank=True, related_name='assigned_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
