# Generated by Django 4.1.7 on 2023-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='capacity',
            field=models.IntegerField(default=12, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='capacity',
            field=models.IntegerField(default=12, verbose_name='Capacity'),
        ),
    ]
