# Generated by Django 5.2.17 on 2026-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_date_capacity_alter_clinic_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_n',
            field=models.CharField(blank=True, max_length=10, verbose_name='Member #'),
        ),
    ]
