# Generated by Django 4.1.10 on 2023-08-24 15:29

from django.db import migrations, models
import reservations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reservations', '0009_member_is_staff_alter_member_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teachingsession',
            name='pro',
        ),
        migrations.AddField(
            model_name='member',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(null=True, validators=[reservations.validators.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Pro',
        ),
        migrations.DeleteModel(
            name='TeachingSession',
        ),
    ]
