# Generated by Django 4.1.10 on 2023-08-24 15:48

from django.db import migrations, models
import reservations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_teachingsession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(default=50, null=True, validators=[reservations.validators.validate_percentage]),
        ),
    ]
